version: 2.0
jobs:
   test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test Step
          command:
            gradle test
      - store_test_results:
          path: build/test-results
   build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Assemple Step
          command:
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
        root: test
        paths:
        - .    
   downstream:
    - attach_workspace:
      at: /tmp/workspace
      
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - build
      - downstream:
        requires:
          - build